### ISSUE TITLE
No SAT Catalogs

### ISSUE THREAD

**Issue by stroker5** [FacturAPI/facturapi-net#10]
Hello!

I am starting to test the platform, however, I found that the FacturapiClient class has no Catalogs, as mentioned in the documentation:
https://docs.facturapi.io/?csharp#cat-logos-sat

![image](https://user-images.githubusercontent.com/8848170/125028217-433b5e80-e04d-11eb-9092-41fd78bb27d0.png)

![image](https://user-images.githubusercontent.com/8848170/125028182-328ae880-e04d-11eb-8053-4b2f82de832f.png)

**Comment by javorosas** [comment]
Solved in last update
