### ISSUE TITLE
Email Method returns error 

### ISSUE THREAD

**Issue by GhostX94-zz** [FacturAPI/facturapi-net#2]
When i run the method SendByEmailAsync returns that error Error: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

why in the doc api says POST https://www.facturapi.io/v1/invoices/{INVOICE_ID}/email
 and here in github says Client_ID

**Comment by javorosas** [comment]
You are right. It should be the invoice Id. I will change that on the README right now.

As for the error, can you tell me how you're calling that method? What parameters are you sending?

**Comment by GhostX94-zz** [comment]
thank you, so could you know why returs this error for try call the method?

ERROR: Error: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

i'm try same with the example set my invoiceID

await facturapi.Invoice.SendByEmailAsync("58e93bd8e86eb318b019743d");

**Comment by javorosas** [comment]
Fixed with the release of version 0.3.2. Please update your NuGet package
