### ISSUE TITLE
Error trying to create invoice

### ISSUE THREAD

**Issue by GhostX94-zz** [FacturAPI/facturapi-net#8]
I've been followin all the steps like the documentation, and when i try to create the customer and product is succes only  the error is when i try to create the invoice is return this error.

Unexpected character encountered while parsing value: {. Path 'items[0].product.id', line 1, position 357.

but my code is exacly like appears in the documentation, please help me for solved.

Thanks and Regards.

![image](https://user-images.githubusercontent.com/36714866/43118004-5eeb03dc-8ed5-11e8-8500-fcee600342d8.png)

**Comment by javorosas** [comment]
Hi, thank you for taking the time to report this issue.

Can you show what your request looks like?

**Comment by GhostX94-zz** [comment]
Of Course, this is the method that i've used since in april for this year, but when i've downloaded the release in when it fails

basically I am sending the information as it appears in the documentation based on .net

![image](https://user-images.githubusercontent.com/36714866/43163569-24588fe4-8f54-11e8-8fd5-0d222e5ae1a0.png)

**Comment by javorosas** [comment]
Can you please check in your dashboard if the invoice is successfully created?

**Comment by GhostX94-zz** [comment]
yes, let me double check

**Comment by GhostX94-zz** [comment]
now I can see them, but if i try to run again my code, do you think now is works?

**Comment by javorosas** [comment]
Not really. First of all, it doesn't looks like it's your code's fault, it's the library. Apparently it is creating the invoice successfully, but when the server responds back, the JSON response cannot be mapped to the C# objects defined in the library.

I will correct this, publish a new version and let you know when it's ready.

Thanks again!

**Comment by GhostX94-zz** [comment]
Thanks for your help, I tried again to make another invoice and returned the same error however, you could tell me what version of Newtonsoft.Json you are using because I use version 11 that downloaded the same update, I appreciate your support and the truth if I am urged by questions that if I use the api in real time.

Thank you

**Comment by GhostX94-zz** [comment]
Hi @javorosas  do you know, some advanced?

**Comment by javorosas** [comment]
Hey Ghost. I was wrong, it was not the library, but out API. We have just published a new release, please let me know wether the problem goes away or not.

Thanks

**Comment by GhostX94** [comment]
I have verified again, and it is correct it is working, thank you very much for your help, on the other hand I wanted to see if we could be contacted, since we have the vision to continue being clients and being able to do business.

Thanks a lot; Regards

Isaac

**Comment by GhostX94-zz** [comment]
I have verified again, and it is correct it is working, thank you very much for your help, on the other hand I wanted to see if we could be contacted, since we have the vision to continue being clients and being able to do business.

Thanks a lot; Regards

Ghost

**Comment by javorosas** [comment]
Sure. Write us anytime at contacto@facturapi.io

Cheers.
