### ISSUE TITLE
Can't create an invoice with foreign trade

### ISSUE THREAD

**Issue by EnriqueVCabada** [FacturAPI/facturapi-net#9]
Hello,
When i'm trying to create an invoice using the foreign trade property, the request completes successfully, but at the moment to see the pdf, the "Valor en Dólares"  label only shows the $NaN text as below.

![image](https://user-images.githubusercontent.com/73904909/98043937-52de1580-1de3-11eb-90d9-9699b54ecc8b.png)

I'm sending a dictionary with "quantity" and "unit_price_usd" properties like this
![image](https://user-images.githubusercontent.com/73904909/98045445-c84ae580-1de5-11eb-80a1-e1e4d36705f4.png)

**Comment by javorosas** [comment]
Esa manera de crear una factura con complemento de comercio exterior fue deprecada. Ahora debes usar el atributo `complements` e insertar la información en el PDF usando `pdf_custom_section`
